import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TABLE "payload_kv" (
  	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  	"key" varchar NOT NULL,
  	"data" jsonb NOT NULL
  );
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_payload_jobs_fk";
  
  ALTER TABLE "header_tabs_nav_items_featured_link_links_locales" DROP CONSTRAINT "header_tabs_nav_items_featured_link_links_locales_parent_id_fk";
  
  DROP INDEX "archiveBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "carouselBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "customHtmlBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "featuredAppsBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "featuresBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "galleryBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "galleryBlock_interactive_gallery_locales_locale_parent_id_unique";
  DROP INDEX "logosBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "metricsBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "pricingBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "pricingBlock_pricing_cards_features_locales_locale_parent_id_unique";
  DROP INDEX "richTextBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "testimonialsBlock_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_archiveBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_carouselBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_customHtmlBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_faqBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_featuredAppsBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_featuresBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_galleryBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_galleryBlock_v_interactive_gallery_locales_locale_parent_id_unique";
  DROP INDEX "_logosBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_metricsBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_pricingBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_pricingBlock_v_pricing_cards_features_locales_locale_parent_id_unique";
  DROP INDEX "_pricingBlock_v_pricing_cards_locales_locale_parent_id_unique";
  DROP INDEX "_richTextBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_testimonialsBlock_v_block_header_links_locales_locale_parent_id_unique";
  DROP INDEX "_pages_v_autosave_idx";
  DROP INDEX "_integrations_v_version_links_locales_locale_parent_id_unique";
  DROP INDEX "media_sizes_thumbnail_sizes_thumbnail_filename_idx";
  DROP INDEX "media_sizes_square_sizes_square_filename_idx";
  DROP INDEX "media_sizes_small_sizes_small_filename_idx";
  DROP INDEX "media_sizes_medium_sizes_medium_filename_idx";
  DROP INDEX "media_sizes_large_sizes_large_filename_idx";
  DROP INDEX "media_sizes_xlarge_sizes_xlarge_filename_idx";
  DROP INDEX "media_sizes_og_sizes_og_filename_idx";
  DROP INDEX "_customers_v_version_testimonial_stats_locales_locale_parent_id_unique";
  DROP INDEX "payload_locked_documents_rels_payload_jobs_id_idx";
  DROP INDEX "header_tabs_description_links_locales_locale_parent_id_unique";
  DROP INDEX "header_tabs_nav_items_featured_link_links_locales_locale_parent_id_unique";
  DROP INDEX "header_tabs_nav_items_list_links_links_locales_locale_parent_id_unique";
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key");
  ALTER TABLE "header_tabs_nav_items_featured_link_links_locales" ADD CONSTRAINT "header_tabs_nav_items_featured_link_links_locales_parent__fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."header_tabs_nav_items_featured_link_links"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "archiveBlock_block_header_links_locales_locale_parent_id_uni" ON "archiveBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "carouselBlock_block_header_links_locales_locale_parent_id_un" ON "carouselBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "customHtmlBlock_block_header_links_locales_locale_parent_id_" ON "customHtmlBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "featuredAppsBlock_block_header_links_locales_locale_parent_i" ON "featuredAppsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "featuresBlock_block_header_links_locales_locale_parent_id_un" ON "featuresBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "galleryBlock_block_header_links_locales_locale_parent_id_uni" ON "galleryBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "galleryBlock_interactive_gallery_locales_locale_parent_id_un" ON "galleryBlock_interactive_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "logosBlock_block_header_links_locales_locale_parent_id_uniqu" ON "logosBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "metricsBlock_block_header_links_locales_locale_parent_id_uni" ON "metricsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pricingBlock_block_header_links_locales_locale_parent_id_uni" ON "pricingBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pricingBlock_pricing_cards_features_locales_locale_parent_id" ON "pricingBlock_pricing_cards_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "richTextBlock_block_header_links_locales_locale_parent_id_un" ON "richTextBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "testimonialsBlock_block_header_links_locales_locale_parent_i" ON "testimonialsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_archiveBlock_v_block_header_links_locales_locale_parent_id_" ON "_archiveBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_carouselBlock_v_block_header_links_locales_locale_parent_id" ON "_carouselBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_customHtmlBlock_v_block_header_links_locales_locale_parent_" ON "_customHtmlBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_faqBlock_v_block_header_links_locales_locale_parent_id_uniq" ON "_faqBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_featuredAppsBlock_v_block_header_links_locales_locale_paren" ON "_featuredAppsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_featuresBlock_v_block_header_links_locales_locale_parent_id" ON "_featuresBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_galleryBlock_v_block_header_links_locales_locale_parent_id_" ON "_galleryBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_galleryBlock_v_interactive_gallery_locales_locale_parent_id" ON "_galleryBlock_v_interactive_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_logosBlock_v_block_header_links_locales_locale_parent_id_un" ON "_logosBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_metricsBlock_v_block_header_links_locales_locale_parent_id_" ON "_metricsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_block_header_links_locales_locale_parent_id_" ON "_pricingBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_pricing_cards_features_locales_locale_parent" ON "_pricingBlock_v_pricing_cards_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_pricing_cards_locales_locale_parent_id_uniqu" ON "_pricingBlock_v_pricing_cards_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_richTextBlock_v_block_header_links_locales_locale_parent_id" ON "_richTextBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_testimonialsBlock_v_block_header_links_locales_locale_paren" ON "_testimonialsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_integrations_v_version_links_locales_locale_parent_id_uniqu" ON "_integrations_v_version_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_customers_v_version_testimonial_stats_locales_locale_parent" ON "_customers_v_version_testimonial_stats_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "header_tabs_description_links_locales_locale_parent_id_uniqu" ON "header_tabs_description_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "header_tabs_nav_items_featured_link_links_locales_locale_par" ON "header_tabs_nav_items_featured_link_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "header_tabs_nav_items_list_links_links_locales_locale_parent" ON "header_tabs_nav_items_list_links_links_locales" USING btree ("_locale","_parent_id");
  ALTER TABLE "_pages_v" DROP COLUMN "autosave";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_url";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_width";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_height";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_thumbnail_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_square_url";
  ALTER TABLE "media" DROP COLUMN "sizes_square_width";
  ALTER TABLE "media" DROP COLUMN "sizes_square_height";
  ALTER TABLE "media" DROP COLUMN "sizes_square_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_square_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_square_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_small_url";
  ALTER TABLE "media" DROP COLUMN "sizes_small_width";
  ALTER TABLE "media" DROP COLUMN "sizes_small_height";
  ALTER TABLE "media" DROP COLUMN "sizes_small_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_small_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_small_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_url";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_width";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_height";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_medium_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_large_url";
  ALTER TABLE "media" DROP COLUMN "sizes_large_width";
  ALTER TABLE "media" DROP COLUMN "sizes_large_height";
  ALTER TABLE "media" DROP COLUMN "sizes_large_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_large_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_large_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_url";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_width";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_height";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_xlarge_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_og_url";
  ALTER TABLE "media" DROP COLUMN "sizes_og_width";
  ALTER TABLE "media" DROP COLUMN "sizes_og_height";
  ALTER TABLE "media" DROP COLUMN "sizes_og_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_og_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_og_filename";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "payload_jobs_id";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "payload_kv" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "payload_kv" CASCADE;
  ALTER TABLE "header_tabs_nav_items_featured_link_links_locales" DROP CONSTRAINT "header_tabs_nav_items_featured_link_links_locales_parent__fk";
  
  DROP INDEX "archiveBlock_block_header_links_locales_locale_parent_id_uni";
  DROP INDEX "carouselBlock_block_header_links_locales_locale_parent_id_un";
  DROP INDEX "customHtmlBlock_block_header_links_locales_locale_parent_id_";
  DROP INDEX "featuredAppsBlock_block_header_links_locales_locale_parent_i";
  DROP INDEX "featuresBlock_block_header_links_locales_locale_parent_id_un";
  DROP INDEX "galleryBlock_block_header_links_locales_locale_parent_id_uni";
  DROP INDEX "galleryBlock_interactive_gallery_locales_locale_parent_id_un";
  DROP INDEX "logosBlock_block_header_links_locales_locale_parent_id_uniqu";
  DROP INDEX "metricsBlock_block_header_links_locales_locale_parent_id_uni";
  DROP INDEX "pricingBlock_block_header_links_locales_locale_parent_id_uni";
  DROP INDEX "pricingBlock_pricing_cards_features_locales_locale_parent_id";
  DROP INDEX "richTextBlock_block_header_links_locales_locale_parent_id_un";
  DROP INDEX "testimonialsBlock_block_header_links_locales_locale_parent_i";
  DROP INDEX "_archiveBlock_v_block_header_links_locales_locale_parent_id_";
  DROP INDEX "_carouselBlock_v_block_header_links_locales_locale_parent_id";
  DROP INDEX "_customHtmlBlock_v_block_header_links_locales_locale_parent_";
  DROP INDEX "_faqBlock_v_block_header_links_locales_locale_parent_id_uniq";
  DROP INDEX "_featuredAppsBlock_v_block_header_links_locales_locale_paren";
  DROP INDEX "_featuresBlock_v_block_header_links_locales_locale_parent_id";
  DROP INDEX "_galleryBlock_v_block_header_links_locales_locale_parent_id_";
  DROP INDEX "_galleryBlock_v_interactive_gallery_locales_locale_parent_id";
  DROP INDEX "_logosBlock_v_block_header_links_locales_locale_parent_id_un";
  DROP INDEX "_metricsBlock_v_block_header_links_locales_locale_parent_id_";
  DROP INDEX "_pricingBlock_v_block_header_links_locales_locale_parent_id_";
  DROP INDEX "_pricingBlock_v_pricing_cards_features_locales_locale_parent";
  DROP INDEX "_pricingBlock_v_pricing_cards_locales_locale_parent_id_uniqu";
  DROP INDEX "_richTextBlock_v_block_header_links_locales_locale_parent_id";
  DROP INDEX "_testimonialsBlock_v_block_header_links_locales_locale_paren";
  DROP INDEX "_integrations_v_version_links_locales_locale_parent_id_uniqu";
  DROP INDEX "_customers_v_version_testimonial_stats_locales_locale_parent";
  DROP INDEX "header_tabs_description_links_locales_locale_parent_id_uniqu";
  DROP INDEX "header_tabs_nav_items_featured_link_links_locales_locale_par";
  DROP INDEX "header_tabs_nav_items_list_links_links_locales_locale_parent";
  ALTER TABLE "_pages_v" ADD COLUMN "autosave" boolean;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_thumbnail_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_square_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_square_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_small_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_small_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_medium_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_large_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_large_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_xlarge_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_og_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_og_filename" varchar;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "payload_jobs_id" uuid;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_payload_jobs_fk" FOREIGN KEY ("payload_jobs_id") REFERENCES "public"."payload_jobs"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "header_tabs_nav_items_featured_link_links_locales" ADD CONSTRAINT "header_tabs_nav_items_featured_link_links_locales_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."header_tabs_nav_items_featured_link_links"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "archiveBlock_block_header_links_locales_locale_parent_id_unique" ON "archiveBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "carouselBlock_block_header_links_locales_locale_parent_id_unique" ON "carouselBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "customHtmlBlock_block_header_links_locales_locale_parent_id_unique" ON "customHtmlBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "featuredAppsBlock_block_header_links_locales_locale_parent_id_unique" ON "featuredAppsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "featuresBlock_block_header_links_locales_locale_parent_id_unique" ON "featuresBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "galleryBlock_block_header_links_locales_locale_parent_id_unique" ON "galleryBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "galleryBlock_interactive_gallery_locales_locale_parent_id_unique" ON "galleryBlock_interactive_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "logosBlock_block_header_links_locales_locale_parent_id_unique" ON "logosBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "metricsBlock_block_header_links_locales_locale_parent_id_unique" ON "metricsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pricingBlock_block_header_links_locales_locale_parent_id_unique" ON "pricingBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "pricingBlock_pricing_cards_features_locales_locale_parent_id_unique" ON "pricingBlock_pricing_cards_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "richTextBlock_block_header_links_locales_locale_parent_id_unique" ON "richTextBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "testimonialsBlock_block_header_links_locales_locale_parent_id_unique" ON "testimonialsBlock_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_archiveBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_archiveBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_carouselBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_carouselBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_customHtmlBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_customHtmlBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_faqBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_faqBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_featuredAppsBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_featuredAppsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_featuresBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_featuresBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_galleryBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_galleryBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_galleryBlock_v_interactive_gallery_locales_locale_parent_id_unique" ON "_galleryBlock_v_interactive_gallery_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_logosBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_logosBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_metricsBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_metricsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_pricingBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_pricing_cards_features_locales_locale_parent_id_unique" ON "_pricingBlock_v_pricing_cards_features_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_pricingBlock_v_pricing_cards_locales_locale_parent_id_unique" ON "_pricingBlock_v_pricing_cards_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_richTextBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_richTextBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "_testimonialsBlock_v_block_header_links_locales_locale_parent_id_unique" ON "_testimonialsBlock_v_block_header_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "_pages_v_autosave_idx" ON "_pages_v" USING btree ("autosave");
  CREATE UNIQUE INDEX "_integrations_v_version_links_locales_locale_parent_id_unique" ON "_integrations_v_version_links_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "media_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "media" USING btree ("sizes_thumbnail_filename");
  CREATE INDEX "media_sizes_square_sizes_square_filename_idx" ON "media" USING btree ("sizes_square_filename");
  CREATE INDEX "media_sizes_small_sizes_small_filename_idx" ON "media" USING btree ("sizes_small_filename");
  CREATE INDEX "media_sizes_medium_sizes_medium_filename_idx" ON "media" USING btree ("sizes_medium_filename");
  CREATE INDEX "media_sizes_large_sizes_large_filename_idx" ON "media" USING btree ("sizes_large_filename");
  CREATE INDEX "media_sizes_xlarge_sizes_xlarge_filename_idx" ON "media" USING btree ("sizes_xlarge_filename");
  CREATE INDEX "media_sizes_og_sizes_og_filename_idx" ON "media" USING btree ("sizes_og_filename");
  CREATE UNIQUE INDEX "_customers_v_version_testimonial_stats_locales_locale_parent_id_unique" ON "_customers_v_version_testimonial_stats_locales" USING btree ("_locale","_parent_id");
  CREATE INDEX "payload_locked_documents_rels_payload_jobs_id_idx" ON "payload_locked_documents_rels" USING btree ("payload_jobs_id");
  CREATE UNIQUE INDEX "header_tabs_description_links_locales_locale_parent_id_unique" ON "header_tabs_description_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "header_tabs_nav_items_featured_link_links_locales_locale_parent_id_unique" ON "header_tabs_nav_items_featured_link_links_locales" USING btree ("_locale","_parent_id");
  CREATE UNIQUE INDEX "header_tabs_nav_items_list_links_links_locales_locale_parent_id_unique" ON "header_tabs_nav_items_list_links_links_locales" USING btree ("_locale","_parent_id");`)
}
