import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."badge_color" ADD VALUE 'purple' BEFORE 'gray';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "archiveBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "archiveBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "callToActionBlock" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "callToActionBlock" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "carouselBlock_columns" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "carouselBlock_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "carouselBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "carouselBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "customHtmlBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "customHtmlBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "faqBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "faqBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "featuredAppsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "featuredAppsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "featuresBlock_columns" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "featuresBlock_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "featuresBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "featuresBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "galleryBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "galleryBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "logosBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "logosBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "metricsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "metricsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "pricingBlock_pricing_cards" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "pricingBlock_pricing_cards" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "pricingBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "pricingBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "richTextBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "richTextBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "testimonialsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "testimonialsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "pages" ALTER COLUMN "hero_badge_color" SET DATA TYPE text;
  ALTER TABLE "pages" ALTER COLUMN "hero_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_archiveBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_archiveBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_callToActionBlock_v" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "_callToActionBlock_v" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_carouselBlock_v_columns" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "_carouselBlock_v_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_carouselBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_carouselBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_customHtmlBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_customHtmlBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_faqBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_faqBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_featuredAppsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_featuredAppsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_featuresBlock_v_columns" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "_featuresBlock_v_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_featuresBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_featuresBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_galleryBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_galleryBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_logosBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_logosBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_metricsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_metricsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_pricingBlock_v_pricing_cards" ALTER COLUMN "badge_color" SET DATA TYPE text;
  ALTER TABLE "_pricingBlock_v_pricing_cards" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_pricingBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_pricingBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_richTextBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_richTextBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_testimonialsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE text;
  ALTER TABLE "_testimonialsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::text;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_badge_color" SET DATA TYPE text;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_badge_color" SET DEFAULT 'blue'::text;
  DROP TYPE "public"."badge_color";
  CREATE TYPE "public"."badge_color" AS ENUM('blue', 'red', 'green', 'yellow', 'gray', 'inverted');
  ALTER TABLE "archiveBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "archiveBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "callToActionBlock" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "callToActionBlock" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "carouselBlock_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "carouselBlock_columns" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "carouselBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "carouselBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "customHtmlBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "customHtmlBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "faqBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "faqBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "featuredAppsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "featuredAppsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "featuresBlock_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "featuresBlock_columns" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "featuresBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "featuresBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "galleryBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "galleryBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "logosBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "logosBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "metricsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "metricsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "pricingBlock_pricing_cards" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "pricingBlock_pricing_cards" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "pricingBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "pricingBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "richTextBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "richTextBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "testimonialsBlock" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "testimonialsBlock" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "pages" ALTER COLUMN "hero_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "pages" ALTER COLUMN "hero_badge_color" SET DATA TYPE "public"."badge_color" USING "hero_badge_color"::"public"."badge_color";
  ALTER TABLE "_archiveBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_archiveBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_callToActionBlock_v" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_callToActionBlock_v" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "_carouselBlock_v_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_carouselBlock_v_columns" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "_carouselBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_carouselBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_customHtmlBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_customHtmlBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_faqBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_faqBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_featuredAppsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_featuredAppsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_featuresBlock_v_columns" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_featuresBlock_v_columns" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "_featuresBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_featuresBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_galleryBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_galleryBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_logosBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_logosBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_metricsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_metricsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_pricingBlock_v_pricing_cards" ALTER COLUMN "badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_pricingBlock_v_pricing_cards" ALTER COLUMN "badge_color" SET DATA TYPE "public"."badge_color" USING "badge_color"::"public"."badge_color";
  ALTER TABLE "_pricingBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_pricingBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_richTextBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_richTextBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_testimonialsBlock_v" ALTER COLUMN "block_header_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_testimonialsBlock_v" ALTER COLUMN "block_header_badge_color" SET DATA TYPE "public"."badge_color" USING "block_header_badge_color"::"public"."badge_color";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_badge_color" SET DEFAULT 'blue'::"public"."badge_color";
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_badge_color" SET DATA TYPE "public"."badge_color" USING "version_hero_badge_color"::"public"."badge_color";`)
}
